import { defineStore } from 'pinia';

export const useEventStore = defineStore('event', {
  state: () => ({
    events: [
      {
        date: '26/04/2020, 12:42 AM',
        eventName: 'May 9th Mukilteo Mixer Standard Doubles Mixer',
        location: 'BBC-Mukilteo',
        signedUp: '25/24',
        signedUpPercent: '99',
        courts: 4,
        status: 'Publish',
      },
      {
        date: '26/04/2020, 12:42 AM',
        eventName: 'May 9th Mukilteo Mixer Standard Doubles Mixer',
        location: 'BBC-Mukilteo',
        signedUp: '25/24',
        signedUpPercent: '99',
        courts: 4,
        status: 'Private',
      },
      {
        date: '26/04/2020, 12:42 AM',
        eventName: 'May 9th Mukilteo Mixer Standard Doubles Mixer',
        location: 'BBC-Mukilteo',
        signedUp: '25/10',
        signedUpPercent: '40',
        courts: 4,
        status: 'Publish',
      },
      {
        date: '26/04/2020, 12:42 AM',
        eventName: 'May 9th Mukilteo Mixer Standard Doubles Mixer',
        location: 'BBC-Mukilteo',
        signedUp: '25/15',
        signedUpPercent: '60',
        courts: 4,
        status: 'Publish',
      },
      {
        date: '26/04/2020, 12:42 AM',
        eventName: 'May 9th Mukilteo Mixer Standard Doubles Mixer',
        location: 'BBC-Mukilteo',
        signedUp: '25/25',
        signedUpPercent: '100',
        courts: 4,
        status: 'Completed',
      },
      {
        date: '26/04/2020, 12:42 AM',
        eventName: 'May 9th Mukilteo Mixer Standard Doubles Mixer',
        location: 'BBC-Mukilteo',
        signedUp: '25/24',
        signedUpPercent: '99',
        courts: 4,
        status: 'Publish',
      },
      {
        date: '26/04/2020, 12:42 AM',
        eventName: 'May 9th Mukilteo Mixer Standard Doubles Mixer',
        location: 'BBC-Mukilteo',
        signedUp: '25/24',
        signedUpPercent: '99',
        courts: 4,
        status: 'Publish',
      },
      {
        date: '26/04/2020, 12:42 AM',
        eventName: 'May 9th Mukilteo Mixer Standard Doubles Mixer',
        location: 'BBC-Mukilteo',
        signedUp: '25/24',
        signedUpPercent: '99',
        courts: 4,
        status: 'Publish',
      },
      {
        date: '26/04/2020, 12:42 AM',
        eventName: 'May 9th Mukilteo Mixer Standard Doubles Mixer',
        location: 'BBC-Mukilteo',
        signedUp: '25/24',
        signedUpPercent: '99',
        courts: 4,
        status: 'Publish',
      },
      {
        date: '26/04/2020, 12:42 AM',
        eventName: 'May 9th Mukilteo Mixer Standard Doubles Mixer',
        location: 'BBC-Mukilteo',
        signedUp: '25/24',
        signedUpPercent: '99',
        courts: 4,
        status: 'Publish',
      },
      {
        date: '26/04/2020, 12:42 AM',
        eventName: 'May 9th Mukilteo Mixer Standard Doubles Mixer',
        location: 'BBC-Mukilteo',
        signedUp: '25/24',
        signedUpPercent: '99',
        courts: 4,
        status: 'Publish',
      },
    ],
    upcomingEvents: [
      {
        date: '26/04/2020, 12:42 AM',
        eventName: 'May 9th Mukilteo Mixer Standard Doubles Mixer',
        location: 'BBC-Mukilteo',
        signedUp: '25/24',
        signedUpPercent: '99',
        courts: 4,
        status: 'Publish',
      },
      {
        date: '26/04/2020, 12:42 AM',
        eventName: 'May 9th Mukilteo Mixer Standard Doubles Mixer',
        location: 'BBC-Mukilteo',
        signedUp: '25/24',
        signedUpPercent: '99',
        courts: 4,
        status: 'Private',
      },
      {
        date: '26/04/2020, 12:42 AM',
        eventName: 'May 9th Mukilteo Mixer Standard Doubles Mixer',
        location: 'BBC-Mukilteo',
        signedUp: '25/10',
        signedUpPercent: '40',
        courts: 4,
        status: 'Publish',
      },
      {
        date: '26/04/2020, 12:42 AM',
        eventName: 'May 9th Mukilteo Mixer Standard Doubles Mixer',
        location: 'BBC-Mukilteo',
        signedUp: '25/15',
        signedUpPercent: '60',
        courts: 4,
        status: 'Publish',
      },
      {
        date: '26/04/2020, 12:42 AM',
        eventName: 'May 9th Mukilteo Mixer Standard Doubles Mixer',
        location: 'BBC-Mukilteo',
        signedUp: '25/24',
        signedUpPercent: '99',
        courts: 4,
        status: 'Publish',
      },
      {
        date: '26/04/2020, 12:42 AM',
        eventName: 'May 9th Mukilteo Mixer Standard Doubles Mixer',
        location: 'BBC-Mukilteo',
        signedUp: '25/24',
        signedUpPercent: '99',
        courts: 4,
        status: 'Publish',
      },
      {
        date: '26/04/2020, 12:42 AM',
        eventName: 'May 9th Mukilteo Mixer Standard Doubles Mixer',
        location: 'BBC-Mukilteo',
        signedUp: '25/24',
        signedUpPercent: '99',
        courts: 4,
        status: 'Publish',
      },
      {
        date: '26/04/2020, 12:42 AM',
        eventName: 'May 9th Mukilteo Mixer Standard Doubles Mixer',
        location: 'BBC-Mukilteo',
        signedUp: '25/24',
        signedUpPercent: '99',
        courts: 4,
        status: 'Publish',
      },
    ],
    pastEvents: [
      {
        date: '26/04/2020, 12:42 AM',
        eventName: 'May 9th Mukilteo Mixer Standard Doubles Mixer',
        location: 'BBC-Mukilteo',
        signedUp: '25/24',
        signedUpPercent: '99',
        courts: 4,
        status: 'Completed',
      },
      {
        date: '26/04/2020, 12:42 AM',
        eventName: 'May 9th Mukilteo Mixer Standard Doubles Mixer',
        location: 'BBC-Mukilteo',
        signedUp: '25/24',
        signedUpPercent: '99',
        courts: 4,
        status: 'Completed',
      },
      {
        date: '26/04/2020, 12:42 AM',
        eventName: 'May 9th Mukilteo Mixer Standard Doubles Mixer',
        location: 'BBC-Mukilteo',
        signedUp: '25/10',
        signedUpPercent: '40',
        courts: 4,
        status: 'Completed',
      },
      {
        date: '26/04/2020, 12:42 AM',
        eventName: 'May 9th Mukilteo Mixer Standard Doubles Mixer',
        location: 'BBC-Mukilteo',
        signedUp: '25/15',
        signedUpPercent: '60',
        courts: 4,
        status: 'Completed',
      },
      {
        date: '26/04/2020, 12:42 AM',
        eventName: 'May 9th Mukilteo Mixer Standard Doubles Mixer',
        location: 'BBC-Mukilteo',
        signedUp: '25/24',
        signedUpPercent: '99',
        courts: 4,
        status: 'Completed',
      },
      {
        date: '26/04/2020, 12:42 AM',
        eventName: 'May 9th Mukilteo Mixer Standard Doubles Mixer',
        location: 'BBC-Mukilteo',
        signedUp: '25/24',
        signedUpPercent: '99',
        courts: 4,
        status: 'Completed',
      },
      {
        date: '26/04/2020, 12:42 AM',
        eventName: 'May 9th Mukilteo Mixer Standard Doubles Mixer',
        location: 'BBC-Mukilteo',
        signedUp: '25/24',
        signedUpPercent: '99',
        courts: 4,
        status: 'Completed',
      },
      {
        date: '26/04/2020, 12:42 AM',
        eventName: 'May 9th Mukilteo Mixer Standard Doubles Mixer',
        location: 'BBC-Mukilteo',
        signedUp: '25/24',
        signedUpPercent: '99',
        courts: 4,
        status: 'Completed',
      },
    ],
  }),
  actions: {
    increment() {
      // this.count++;
    },
  },
});
